# Generated by Django 5.1.4 on 2024-12-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=400)),
            ],
            options={
                'verbose_name': 'Description',
                'db_table': 'description',
            },
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Telefon raqamini kiriting.', max_length=100)),
                ('email', models.EmailField(help_text='Email manzilini kiriting.', max_length=254)),
                ('address', models.TextField(help_text='Manzilni kiriting.', max_length=100)),
                ('instagram', models.URLField(blank=True, help_text='Instagram profilining URL manzilini kiriting.', null=True)),
                ('telegram', models.URLField(blank=True, help_text='Telegram kanal yoki profil URL manzilini kiriting.', null=True)),
                ('youtube', models.URLField(blank=True, help_text='YouTube kanalining URL manzilini kiriting.', null=True)),
            ],
            options={
                'verbose_name': 'Kontakt',
                'db_table': 'kontakt',
            },
        ),
        migrations.CreateModel(
            name='DocumentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, help_text='Faylni yuklang', null=True, upload_to='documents/')),
                ('document_img', models.ImageField(blank=True, null=True, upload_to='document_img/')),
            ],
            options={
                'verbose_name': 'Document',
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='GalleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery', models.ImageField(upload_to='school_img/')),
            ],
            options={
                'verbose_name': 'Galereya',
                'db_table': 'galereya',
            },
        ),
        migrations.CreateModel(
            name='TeachersModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_img', models.ImageField(upload_to='teacher_img/')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "O'qituvchilar",
                'db_table': 'oqituvchilar',
            },
        ),
    ]
