# Generated by Django 5.1.4 on 2024-12-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutmodel',
            options={'verbose_name': 'Biz haqimizda', 'verbose_name_plural': 'Biz haqimizda'},
        ),
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name': 'Kontakt', 'verbose_name_plural': 'Kontaktlar'},
        ),
        migrations.AlterModelOptions(
            name='documentmodel',
            options={'verbose_name': 'Dokumentlar'},
        ),
        migrations.AlterModelOptions(
            name='gallerymodel',
            options={'verbose_name': 'Rasm', 'verbose_name_plural': 'Rasmlar'},
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='description',
            field=models.TextField(help_text='Maktab haqida malumot yozing.', max_length=400),
        ),
        migrations.AlterField(
            model_name='documentmodel',
            name='document_img',
            field=models.ImageField(blank=True, help_text='Dokument uchun rasm yuklang', null=True, upload_to='document_img/'),
        ),
        migrations.AlterField(
            model_name='gallerymodel',
            name='gallery',
            field=models.ImageField(help_text='Maktab rasmini yuklang', upload_to='school_img/'),
        ),
        migrations.AlterField(
            model_name='teachersmodal',
            name='first_name',
            field=models.CharField(help_text="O'qituvchinig ismini kiriting", max_length=100),
        ),
        migrations.AlterField(
            model_name='teachersmodal',
            name='last_name',
            field=models.CharField(help_text="O'qituvchinig familiyasini kiriting", max_length=100),
        ),
        migrations.AlterField(
            model_name='teachersmodal',
            name='teacher_img',
            field=models.ImageField(help_text="O'qituvchining rasmini yuklang", upload_to='teacher_img/'),
        ),
    ]
