# Generated by Django 5.1.4 on 2024-12-16 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_aboutmodel_options_alter_contactmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentmodel',
            options={'verbose_name': 'Dokument', 'verbose_name_plural': 'Dokumentlar'},
        ),
    ]
