# Generated by Django 5.1.4 on 2024-12-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_documentmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmodel',
            name='description',
            field=models.TextField(help_text='Maktab haqida malumot yozing.'),
        ),
    ]
