# Generated by Django 5.1.4 on 2024-12-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_teachersmodal_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Yangilik mavzusini kiriting', max_length=100)),
                ('news', models.TextField(help_text='Yangigilikni kiriting', max_length=2000)),
                ('news_img', models.ImageField(upload_to='news/')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'db_table': 'news',
            },
        ),
    ]
