# Generated by Django 5.1.4 on 2024-12-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_newsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='location',
            field=models.FileField(default='nothing', help_text="Manzilingizni xaritada ko'rsatish uchun joylashuvni kiriting.", upload_to=''),
            preserve_default=False,
        ),
    ]
