# Generated by Django 5.1.4 on 2024-12-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_alter_contactmodel_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='location',
            field=models.URLField(help_text="Manzilingizni xaritada ko'rsatish uchun joylashuvni kiriting."),
        ),
    ]
